package modelos;
// Generated 1/02/2020 07:18:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AdicionalGriferia generated by hbm2java
 */
public class AdicionalGriferia  implements java.io.Serializable {


     private Integer adicionalGriferiaId;
     private String descripcion;
     private Double precio;
     private Set casaCreadaAdicionals = new HashSet(0);

    public AdicionalGriferia() {
    }

    public AdicionalGriferia(String descripcion, Double precio, Set casaCreadaAdicionals) {
       this.descripcion = descripcion;
       this.precio = precio;
       this.casaCreadaAdicionals = casaCreadaAdicionals;
    }
   
    public Integer getAdicionalGriferiaId() {
        return this.adicionalGriferiaId;
    }
    
    public void setAdicionalGriferiaId(Integer adicionalGriferiaId) {
        this.adicionalGriferiaId = adicionalGriferiaId;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public Set getCasaCreadaAdicionals() {
        return this.casaCreadaAdicionals;
    }
    
    public void setCasaCreadaAdicionals(Set casaCreadaAdicionals) {
        this.casaCreadaAdicionals = casaCreadaAdicionals;
    }




}


