package modelos;
// Generated 1/02/2020 07:18:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AdicionalBanios generated by hbm2java
 */
public class AdicionalBanios  implements java.io.Serializable {


     private Integer adicionalBaniosId;
     private String descripcion;
     private Double precio;
     private Set casaCreadaAdicionals = new HashSet(0);

    public AdicionalBanios() {
    }

    public AdicionalBanios(String descripcion, Double precio, Set casaCreadaAdicionals) {
       this.descripcion = descripcion;
       this.precio = precio;
       this.casaCreadaAdicionals = casaCreadaAdicionals;
    }
   
    public Integer getAdicionalBaniosId() {
        return this.adicionalBaniosId;
    }
    
    public void setAdicionalBaniosId(Integer adicionalBaniosId) {
        this.adicionalBaniosId = adicionalBaniosId;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public Set getCasaCreadaAdicionals() {
        return this.casaCreadaAdicionals;
    }
    
    public void setCasaCreadaAdicionals(Set casaCreadaAdicionals) {
        this.casaCreadaAdicionals = casaCreadaAdicionals;
    }




}


