package modelos;
// Generated 2/02/2020 10:33:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Adicionaltecho generated by hbm2java
 */
public class Adicionaltecho  implements java.io.Serializable {


     private Integer adicionalTechoId;
     private String descripcion;
     private Double precio;
     private Set casacreadaAdicionals = new HashSet(0);

    public Adicionaltecho() {
    }

    public Adicionaltecho(String descripcion, Double precio, Set casacreadaAdicionals) {
       this.descripcion = descripcion;
       this.precio = precio;
       this.casacreadaAdicionals = casacreadaAdicionals;
    }
   
    public Integer getAdicionalTechoId() {
        return this.adicionalTechoId;
    }
    
    public void setAdicionalTechoId(Integer adicionalTechoId) {
        this.adicionalTechoId = adicionalTechoId;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public Set getCasacreadaAdicionals() {
        return this.casacreadaAdicionals;
    }
    
    public void setCasacreadaAdicionals(Set casacreadaAdicionals) {
        this.casacreadaAdicionals = casacreadaAdicionals;
    }

    @Override
    public String toString() {
        return descripcion;
    }
    



}


