package modelos;
// Generated 2/02/2020 09:19:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cargo generated by hbm2java
 */
public class Cargo  implements java.io.Serializable {


     private Integer cargoId;
     private String descripcion;
     private Set empleados = new HashSet(0);
     private Set clientes = new HashSet(0);

    public Cargo() {
    }

	
    public Cargo(String descripcion) {
        this.descripcion = descripcion;
    }
    public Cargo(String descripcion, Set empleados, Set clientes) {
       this.descripcion = descripcion;
       this.empleados = empleados;
       this.clientes = clientes;
    }
   
    public Integer getCargoId() {
        return this.cargoId;
    }
    
    public void setCargoId(Integer cargoId) {
        this.cargoId = cargoId;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


