package modelos;
// Generated 2/02/2020 09:19:52 PM by Hibernate Tools 4.3.1



/**
 * CasacreadaAdicional generated by hbm2java
 */
public class CasacreadaAdicional  implements java.io.Serializable {


     private int casaCreadaAdicional;
     private Adicionalbanios adicionalbanios;
     private Adicionalgriferia adicionalgriferia;
     private Adicionaliluminacion adicionaliluminacion;
     private Adicionalpiso adicionalpiso;
     private Adicionaltecho adicionaltecho;
     private Casacreada casacreada;
     private int adicionalId;

    public CasacreadaAdicional() {
    }

	
    public CasacreadaAdicional(int casaCreadaAdicional, Casacreada casacreada, int adicionalId) {
        this.casaCreadaAdicional = casaCreadaAdicional;
        this.casacreada = casacreada;
        this.adicionalId = adicionalId;
    }
    public CasacreadaAdicional(int casaCreadaAdicional, Adicionalbanios adicionalbanios, Adicionalgriferia adicionalgriferia, Adicionaliluminacion adicionaliluminacion, Adicionalpiso adicionalpiso, Adicionaltecho adicionaltecho, Casacreada casacreada, int adicionalId) {
       this.casaCreadaAdicional = casaCreadaAdicional;
       this.adicionalbanios = adicionalbanios;
       this.adicionalgriferia = adicionalgriferia;
       this.adicionaliluminacion = adicionaliluminacion;
       this.adicionalpiso = adicionalpiso;
       this.adicionaltecho = adicionaltecho;
       this.casacreada = casacreada;
       this.adicionalId = adicionalId;
    }
   
    public int getCasaCreadaAdicional() {
        return this.casaCreadaAdicional;
    }
    
    public void setCasaCreadaAdicional(int casaCreadaAdicional) {
        this.casaCreadaAdicional = casaCreadaAdicional;
    }
    public Adicionalbanios getAdicionalbanios() {
        return this.adicionalbanios;
    }
    
    public void setAdicionalbanios(Adicionalbanios adicionalbanios) {
        this.adicionalbanios = adicionalbanios;
    }
    public Adicionalgriferia getAdicionalgriferia() {
        return this.adicionalgriferia;
    }
    
    public void setAdicionalgriferia(Adicionalgriferia adicionalgriferia) {
        this.adicionalgriferia = adicionalgriferia;
    }
    public Adicionaliluminacion getAdicionaliluminacion() {
        return this.adicionaliluminacion;
    }
    
    public void setAdicionaliluminacion(Adicionaliluminacion adicionaliluminacion) {
        this.adicionaliluminacion = adicionaliluminacion;
    }
    public Adicionalpiso getAdicionalpiso() {
        return this.adicionalpiso;
    }
    
    public void setAdicionalpiso(Adicionalpiso adicionalpiso) {
        this.adicionalpiso = adicionalpiso;
    }
    public Adicionaltecho getAdicionaltecho() {
        return this.adicionaltecho;
    }
    
    public void setAdicionaltecho(Adicionaltecho adicionaltecho) {
        this.adicionaltecho = adicionaltecho;
    }
    public Casacreada getCasacreada() {
        return this.casacreada;
    }
    
    public void setCasacreada(Casacreada casacreada) {
        this.casacreada = casacreada;
    }
    public int getAdicionalId() {
        return this.adicionalId;
    }
    
    public void setAdicionalId(int adicionalId) {
        this.adicionalId = adicionalId;
    }




}


