package modelos;
// Generated 2/02/2020 08:19:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Casacreada generated by hbm2java
 */
public class Casacreada  implements java.io.Serializable {


     private Integer casaAdicionalId;
     private Casabuilder casabuilder;
     private Set empleadocreacasas = new HashSet(0);
     private Set casacreadaAdicionals = new HashSet(0);
     private Set cotizacions = new HashSet(0);

    public Casacreada() {
    }

	
    public Casacreada(Casabuilder casabuilder) {
        this.casabuilder = casabuilder;
    }
    public Casacreada(Casabuilder casabuilder, Set empleadocreacasas, Set casacreadaAdicionals, Set cotizacions) {
       this.casabuilder = casabuilder;
       this.empleadocreacasas = empleadocreacasas;
       this.casacreadaAdicionals = casacreadaAdicionals;
       this.cotizacions = cotizacions;
    }
   
    public Integer getCasaAdicionalId() {
        return this.casaAdicionalId;
    }
    
    public void setCasaAdicionalId(Integer casaAdicionalId) {
        this.casaAdicionalId = casaAdicionalId;
    }
    public Casabuilder getCasabuilder() {
        return this.casabuilder;
    }
    
    public void setCasabuilder(Casabuilder casabuilder) {
        this.casabuilder = casabuilder;
    }
    public Set getEmpleadocreacasas() {
        return this.empleadocreacasas;
    }
    
    public void setEmpleadocreacasas(Set empleadocreacasas) {
        this.empleadocreacasas = empleadocreacasas;
    }
    public Set getCasacreadaAdicionals() {
        return this.casacreadaAdicionals;
    }
    
    public void setCasacreadaAdicionals(Set casacreadaAdicionals) {
        this.casacreadaAdicionals = casacreadaAdicionals;
    }
    public Set getCotizacions() {
        return this.cotizacions;
    }
    
    public void setCotizacions(Set cotizacions) {
        this.cotizacions = cotizacions;
    }




}


