package modelos;
// Generated 1/02/2020 07:18:57 PM by Hibernate Tools 4.3.1



/**
 * CasaCreadaAdicional generated by hbm2java
 */
public class CasaCreadaAdicional  implements java.io.Serializable {


     private int casaCreadaAdicional;
     private AdicionalBanios adicionalBanios;
     private AdicionalGriferia adicionalGriferia;
     private AdicionalIluminacion adicionalIluminacion;
     private AdicionalPiso adicionalPiso;
     private AdicionalTecho adicionalTecho;
     private CasaCreada casaCreada;
     private int adicionalId;

    public CasaCreadaAdicional() {
    }

	
    public CasaCreadaAdicional(int casaCreadaAdicional, CasaCreada casaCreada, int adicionalId) {
        this.casaCreadaAdicional = casaCreadaAdicional;
        this.casaCreada = casaCreada;
        this.adicionalId = adicionalId;
    }
    public CasaCreadaAdicional(int casaCreadaAdicional, AdicionalBanios adicionalBanios, AdicionalGriferia adicionalGriferia, AdicionalIluminacion adicionalIluminacion, AdicionalPiso adicionalPiso, AdicionalTecho adicionalTecho, CasaCreada casaCreada, int adicionalId) {
       this.casaCreadaAdicional = casaCreadaAdicional;
       this.adicionalBanios = adicionalBanios;
       this.adicionalGriferia = adicionalGriferia;
       this.adicionalIluminacion = adicionalIluminacion;
       this.adicionalPiso = adicionalPiso;
       this.adicionalTecho = adicionalTecho;
       this.casaCreada = casaCreada;
       this.adicionalId = adicionalId;
    }
   
    public int getCasaCreadaAdicional() {
        return this.casaCreadaAdicional;
    }
    
    public void setCasaCreadaAdicional(int casaCreadaAdicional) {
        this.casaCreadaAdicional = casaCreadaAdicional;
    }
    public AdicionalBanios getAdicionalBanios() {
        return this.adicionalBanios;
    }
    
    public void setAdicionalBanios(AdicionalBanios adicionalBanios) {
        this.adicionalBanios = adicionalBanios;
    }
    public AdicionalGriferia getAdicionalGriferia() {
        return this.adicionalGriferia;
    }
    
    public void setAdicionalGriferia(AdicionalGriferia adicionalGriferia) {
        this.adicionalGriferia = adicionalGriferia;
    }
    public AdicionalIluminacion getAdicionalIluminacion() {
        return this.adicionalIluminacion;
    }
    
    public void setAdicionalIluminacion(AdicionalIluminacion adicionalIluminacion) {
        this.adicionalIluminacion = adicionalIluminacion;
    }
    public AdicionalPiso getAdicionalPiso() {
        return this.adicionalPiso;
    }
    
    public void setAdicionalPiso(AdicionalPiso adicionalPiso) {
        this.adicionalPiso = adicionalPiso;
    }
    public AdicionalTecho getAdicionalTecho() {
        return this.adicionalTecho;
    }
    
    public void setAdicionalTecho(AdicionalTecho adicionalTecho) {
        this.adicionalTecho = adicionalTecho;
    }
    public CasaCreada getCasaCreada() {
        return this.casaCreada;
    }
    
    public void setCasaCreada(CasaCreada casaCreada) {
        this.casaCreada = casaCreada;
    }
    public int getAdicionalId() {
        return this.adicionalId;
    }
    
    public void setAdicionalId(int adicionalId) {
        this.adicionalId = adicionalId;
    }




}


