package modelos;
// Generated 2/02/2020 09:19:52 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cotizacion generated by hbm2java
 */
public class Cotizacion  implements java.io.Serializable {


     private int cotizacionId;
     private Casacreada casacreada;
     private Cliente cliente;
     private Date fecha;
     private double precio;

    public Cotizacion() {
    }

    public Cotizacion(int cotizacionId, Casacreada casacreada, Cliente cliente, Date fecha, double precio) {
       this.cotizacionId = cotizacionId;
       this.casacreada = casacreada;
       this.cliente = cliente;
       this.fecha = fecha;
       this.precio = precio;
    }
   
    public int getCotizacionId() {
        return this.cotizacionId;
    }
    
    public void setCotizacionId(int cotizacionId) {
        this.cotizacionId = cotizacionId;
    }
    public Casacreada getCasacreada() {
        return this.casacreada;
    }
    
    public void setCasacreada(Casacreada casacreada) {
        this.casacreada = casacreada;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }




}


