package modelos;
// Generated 2/02/2020 10:33:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Direccion generated by hbm2java
 */
public class Direccion  implements java.io.Serializable {


     private Integer direccionId;
     private Canton canton;
     private String descripcion;
     private Set clientes = new HashSet(0);
     private Set empleados = new HashSet(0);

    public Direccion() {
    }

	
    public Direccion(Canton canton, String descripcion) {
        this.canton = canton;
        this.descripcion = descripcion;
    }
    public Direccion(Canton canton, String descripcion, Set clientes, Set empleados) {
       this.canton = canton;
       this.descripcion = descripcion;
       this.clientes = clientes;
       this.empleados = empleados;
    }
   
    public Integer getDireccionId() {
        return this.direccionId;
    }
    
    public void setDireccionId(Integer direccionId) {
        this.direccionId = direccionId;
    }
    public Canton getCanton() {
        return this.canton;
    }
    
    public void setCanton(Canton canton) {
        this.canton = canton;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }




}


