package modelos;
// Generated 1/02/2020 07:18:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private int empleadoId;
     private Cargo cargo;
     private Direccion direccion;
     private EstadoCivil estadoCivil;
     private String nombres;
     private String apellidos;
     private String telefono;
     private String correo;
     private String activo;
     private Set empleadoCreaCasas = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(int empleadoId, Cargo cargo, Direccion direccion, EstadoCivil estadoCivil, String nombres, String apellidos, String telefono, String correo, String activo) {
        this.empleadoId = empleadoId;
        this.cargo = cargo;
        this.direccion = direccion;
        this.estadoCivil = estadoCivil;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.telefono = telefono;
        this.correo = correo;
        this.activo = activo;
    }
    public Empleado(int empleadoId, Cargo cargo, Direccion direccion, EstadoCivil estadoCivil, String nombres, String apellidos, String telefono, String correo, String activo, Set empleadoCreaCasas) {
       this.empleadoId = empleadoId;
       this.cargo = cargo;
       this.direccion = direccion;
       this.estadoCivil = estadoCivil;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.telefono = telefono;
       this.correo = correo;
       this.activo = activo;
       this.empleadoCreaCasas = empleadoCreaCasas;
    }
   
    public int getEmpleadoId() {
        return this.empleadoId;
    }
    
    public void setEmpleadoId(int empleadoId) {
        this.empleadoId = empleadoId;
    }
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }
    public Direccion getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(Direccion direccion) {
        this.direccion = direccion;
    }
    public EstadoCivil getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(EstadoCivil estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }
    public Set getEmpleadoCreaCasas() {
        return this.empleadoCreaCasas;
    }
    
    public void setEmpleadoCreaCasas(Set empleadoCreaCasas) {
        this.empleadoCreaCasas = empleadoCreaCasas;
    }




}


