package modelos;
// Generated 2/02/2020 08:19:21 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Empleadocreacasa generated by hbm2java
 */
public class Empleadocreacasa  implements java.io.Serializable {


     private Integer empleadoCasaCreadaId;
     private Casacreada casacreada;
     private Empleado empleado;
     private Date fecha;

    public Empleadocreacasa() {
    }

    public Empleadocreacasa(Casacreada casacreada, Empleado empleado, Date fecha) {
       this.casacreada = casacreada;
       this.empleado = empleado;
       this.fecha = fecha;
    }
   
    public Integer getEmpleadoCasaCreadaId() {
        return this.empleadoCasaCreadaId;
    }
    
    public void setEmpleadoCasaCreadaId(Integer empleadoCasaCreadaId) {
        this.empleadoCasaCreadaId = empleadoCasaCreadaId;
    }
    public Casacreada getCasacreada() {
        return this.casacreada;
    }
    
    public void setCasacreada(Casacreada casacreada) {
        this.casacreada = casacreada;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


