package modelos;
// Generated 1/02/2020 07:18:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EstadoCivil generated by hbm2java
 */
public class EstadoCivil  implements java.io.Serializable {


     private Integer estadoCivilId;
     private String descripcion;
     private Set empleados = new HashSet(0);
     private Set clientes = new HashSet(0);

    public EstadoCivil() {
    }

	
    public EstadoCivil(String descripcion) {
        this.descripcion = descripcion;
    }
    public EstadoCivil(String descripcion, Set empleados, Set clientes) {
       this.descripcion = descripcion;
       this.empleados = empleados;
       this.clientes = clientes;
    }
   
    public Integer getEstadoCivilId() {
        return this.estadoCivilId;
    }
    
    public void setEstadoCivilId(Integer estadoCivilId) {
        this.estadoCivilId = estadoCivilId;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


