package modelos;
// Generated 1/02/2020 07:18:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Provincia generated by hbm2java
 */
public class Provincia  implements java.io.Serializable {


     private Integer provinciaId;
     private Pais pais;
     private String descripcion;
     private Set cantons = new HashSet(0);

    public Provincia() {
    }

	
    public Provincia(Pais pais, String descripcion) {
        this.pais = pais;
        this.descripcion = descripcion;
    }
    public Provincia(Pais pais, String descripcion, Set cantons) {
       this.pais = pais;
       this.descripcion = descripcion;
       this.cantons = cantons;
    }
   
    public Integer getProvinciaId() {
        return this.provinciaId;
    }
    
    public void setProvinciaId(Integer provinciaId) {
        this.provinciaId = provinciaId;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getCantons() {
        return this.cantons;
    }
    
    public void setCantons(Set cantons) {
        this.cantons = cantons;
    }




}


